# Generated by Django 3.0.4 on 2020-03-13 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtaulu',
            name='col',
        ),
        migrations.AddField(
            model_name='testtaulu',
            name='alkupera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.TestTaulu'),
        ),
        migrations.AddField(
            model_name='testtaulu',
            name='alkuperamaa',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='testtaulu',
            name='lisaaja',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testtaulu',
            name='pva',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='testtaulu',
            name='sairaanhoitopiiri',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
