# Generated by Django 3.0.4 on 2020-03-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200313_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaulu',
            name='alkupera',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
