# Generated by Django 3.0.4 on 2020-04-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200313_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtaulu',
            name='pva',
            field=models.DateTimeField(default=None),
        ),
    ]
