# Generated by Django 3.0.4 on 2020-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200401_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaulu',
            name='potilasid',
            field=models.IntegerField(default=None),
        ),
    ]
