# Generated by Django 3.0.4 on 2020-04-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200401_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuolemaTaulu',
            fields=[
                ('kuolemaid', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('pva', models.DateTimeField(default=None)),
                ('sairaanhoitopiiri', models.CharField(default=None, max_length=25, null=True)),
            ],
        ),
    ]
