# Generated by Django 3.0.4 on 2020-04-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_kuolemataulu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuolemataulu',
            name='pva',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='testtaulu',
            name='pva',
            field=models.DateField(default=None),
        ),
    ]
